package com.timebox.android.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * The design's CSS custom properties, one field per `--token`.
 *
 * Names follow the design document so the two stay diffable: `bg`, `low`, `onv`,
 * `psurf` and friends are the same tokens declared on `.tb` / `.tb.dark`.
 */
@Immutable
data class TimeboxColors(
    val primary: Color,
    val onPrimary: Color,
    val action: Color,
    val onAction: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val bg: Color,
    val lowest: Color,
    val low: Color,
    val surf: Color,
    val high: Color,
    val highest: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    /** Semantic surface ladder used by product components, from embedded to raised. */
    val field: Color,
    val card: Color,
    val raised: Color,
    val selected: Color,
    val onSelected: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val on: Color,
    val onVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val hairline: Color,
    val planned: Color,
    val plannedSurface: Color,
    val plannedBorder: Color,
    val actual: Color,
    val actualSurface: Color,
    val actualBorder: Color,
    val gridStrong: Color,
    val gridSoft: Color,
    val timelineLabel: Color,
    val now: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val paper: Color,
    val paperRaised: Color,
    val rule: Color,
    val groove: Color,
    val sheet: Color,
    val scrim: Color,
    val isDark: Boolean,
)

val LightTimeboxColors = TimeboxColors(
    primary = Color(0xFF5D5E61),
    onPrimary = Color(0xFFF7F7FA),
    action = Color(0xFF5D5E61),
    onAction = Color(0xFFF7F7FA),
    primaryContainer = Color(0xFFE2E2E5),
    onPrimaryContainer = Color(0xFF505254),
    secondary = Color(0xFF5F5F5F),
    onSecondary = Color(0xFFFAF8F8),
    secondaryContainer = Color(0xFFE4E2E2),
    onSecondaryContainer = Color(0xFF515252),
    bg = Color(0xFFF9F9F9),
    lowest = Color(0xFFFFFFFF),
    low = Color(0xFFF2F4F4),
    surf = Color(0xFFEBEEEF),
    high = Color(0xFFE4E9EA),
    highest = Color(0xFFDDE4E5),
    surfaceDim = Color(0xFFD4DBDD),
    surfaceBright = Color(0xFFF9F9F9),
    field = Color(0xFFFFFFFF),
    card = Color(0xFFF2F4F4),
    raised = Color(0xFFFFFFFF),
    selected = Color(0xFFE2E2E5),
    onSelected = Color(0xFF454749),
    disabledContainer = Color(0xFFE1E4E5),
    disabledContent = Color(0xFF5A6061),
    on = Color(0xFF2D3435),
    onVariant = Color(0xFF5A6061),
    outline = Color(0xFF757C7D),
    outlineVariant = Color(0xFFADB3B4),
    hairline = Color(0x59ADB3B4), // --ov15: rgba(173,179,180,.35)
    planned = Color(0xFF1967D2),
    plannedSurface = Color(0xFFF5F9FF),
    plannedBorder = Color(0xFFC5D9F7),
    actual = Color(0xFF0D6B63),
    actualSurface = Color(0xFFF2FAF9),
    actualBorder = Color(0xFFB5DED6),
    gridStrong = Color(0xFFDADCE0),
    gridSoft = Color(0xFFE8EAED),
    timelineLabel = Color(0xFF5F6368),
    now = Color(0xFF9F403D),
    error = Color(0xFF9F403D),
    onError = Color(0xFFFFF7F6),
    errorContainer = Color(0xFFFE8983),
    onErrorContainer = Color(0xFF752121),
    tertiary = Color(0xFF5C605E),
    onTertiary = Color(0xFFF7F9F7),
    tertiaryContainer = Color(0xFFE9ECE9),
    onTertiaryContainer = Color(0xFF545756),
    inverseSurface = Color(0xFF0C0F0F),
    inverseOnSurface = Color(0xFF9C9D9D),
    inversePrimary = Color(0xFFF9F9FC),
    paper = Color(0xFFEDE8D8),
    paperRaised = Color(0xFFFEFCF5),
    rule = Color(0x73322814), // rgba(50,40,20,.45)
    groove = Color(0x0F322814), // rgba(50,40,20,.06)
    sheet = Color(0xEBFFFFFF), // rgba(255,255,255,.92)
    scrim = Color(0x522D3435), // rgba(45,52,53,.32)
    isDark = false,
)

val DarkTimeboxColors = TimeboxColors(
    primary = Color(0xFFC8C7CB),
    onPrimary = Color(0xFF303033),
    action = Color(0xFF5D5E61),
    onAction = Color(0xFFF7F7FA),
    primaryContainer = Color(0xFF454649),
    onPrimaryContainer = Color(0xFFE2E2E5),
    secondary = Color(0xFFC7C6C6),
    onSecondary = Color(0xFF303030),
    secondaryContainer = Color(0xFF464545),
    onSecondaryContainer = Color(0xFFE4E2E2),
    bg = Color(0xFF0C0A09),
    lowest = Color(0xFF0C0A09),
    low = Color(0xFF1C1917),
    surf = Color(0xFF292524),
    high = Color(0xFF44403C),
    highest = Color(0xFF57534E),
    surfaceDim = Color(0xFF0C0A09),
    surfaceBright = Color(0xFF393532),
    field = Color(0xFF1C1917),
    card = Color(0xFF1C1917),
    raised = Color(0xFF292524),
    selected = Color(0xFF454649),
    onSelected = Color(0xFFE2E2E5),
    disabledContainer = Color(0xFF34302E),
    disabledContent = Color(0xFFA8A29E),
    on = Color(0xFFF5F5F4),
    onVariant = Color(0xFFA8A29E),
    outline = Color(0xFF78716C),
    outlineVariant = Color(0xFF44403C),
    hairline = Color(0xE644403C), // --ov15: rgba(68,64,60,.9)
    planned = Color(0xFF8AB4F8),
    plannedSurface = Color(0xFF0F141C),
    plannedBorder = Color(0xFF2A3F55),
    actual = Color(0xFF7DD3C8),
    actualSurface = Color(0xFF0C1211),
    actualBorder = Color(0xFF1E3D38),
    gridStrong = Color(0xFF44403C),
    gridSoft = Color(0xFF292524),
    timelineLabel = Color(0xFFA8A29E),
    now = Color(0xFF9F403D),
    error = Color(0xFFF2A09A),
    onError = Color(0xFF4B0D0B),
    errorContainer = Color(0xFF6B1F1B),
    onErrorContainer = Color(0xFFFFDAD6),
    tertiary = Color(0xFFC3C8C5),
    onTertiary = Color(0xFF2D312F),
    tertiaryContainer = Color(0xFF444946),
    onTertiaryContainer = Color(0xFFE0E4E1),
    inverseSurface = Color(0xFFF5F5F4),
    inverseOnSurface = Color(0xFF2D2927),
    inversePrimary = Color(0xFF5D5E61),
    paper = Color(0xFF1C1917),
    paperRaised = Color(0xFF292524),
    rule = Color(0x4DFFFAF0), // rgba(255,250,240,.3)
    groove = Color(0x4D000000), // rgba(0,0,0,.3)
    sheet = Color(0xF01C1917), // rgba(28,25,23,.94)
    scrim = Color(0x80000000), // rgba(0,0,0,.5)
    isDark = true,
)
