"""Bounds shared by generation, presentation and rolling context."""

MAX_READ_ROUNDS = 5
MAX_MODEL_CALLS = MAX_READ_ROUNDS + 2  # Optional proposal, then a tool-free answer.
MAX_PROPOSALS = 1
MAX_CARDS = 3
MAX_CONTEXT_EXCHANGES = 20
RESPONSE_TIMEOUT = 120
MAX_TASK_PAGE = 20
MAX_TASK_MANIFEST = 1000
MAX_REFRESH_IDENTITIES = 40
TASK_READ_TIMEOUT = 5
TASK_CURSOR_SECONDS = 15 * 60
MAX_TASK_PARENTS = 5
MAX_TASK_OPERATIONS = 20
MAX_TASK_REVIEW_BYTES = 64 * 1024
MAX_TASK_RECEIPT_BYTES = 64 * 1024
MAX_DESCRIPTION_CHARACTERS = 8000
MAX_DESCRIPTION_BYTES = 16 * 1024
TASK_PROPOSAL_SECONDS = 15 * 60
TASK_ADMISSION_SECONDS = 5
TASK_TRANSACTION_SECONDS = 10
TASK_REQUEST_SECONDS = 20
MAX_TASK_OUTCOMES = 20
