async page => {
  await page.reload()
  await page.getByRole('button', { name: 'View', exact: true }).click()
  const check = (value, message) => { if (!value) throw new Error(message) }
  const toggle = name => page.getByRole('switch', { name, exact: true })
  check(await toggle('Calendar').getAttribute('aria-checked') === 'true', 'Calendar default')
  check(await toggle('Zoom').getAttribute('aria-checked') === 'false', 'Zoom default')
  check(await toggle('Activity Tracking').getAttribute('aria-checked') === 'false', 'Tracking default')
  await toggle('Calendar').click()
  await toggle('Zoom').click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByLabel('Timeline zoom 1.0 times. Use arrow keys to adjust.', { exact: true }).press('ArrowUp')
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await toggle('Zoom').click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  check(await page.getByLabel(/Timeline zoom/).count() === 0, 'Zoom did not hide')
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await toggle('Zoom').click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  check(await page.getByLabel('Timeline zoom 1.2 times. Use arrow keys to adjust.', { exact: true }).count() === 1, 'Hiding reset zoom')
  await page.reload()
  await page.getByRole('button', { name: 'View', exact: true }).click()
  check(await toggle('Calendar').getAttribute('aria-checked') === 'false', 'Calendar did not persist')
  check(await toggle('Zoom').getAttribute('aria-checked') === 'true', 'Zoom did not persist')
  await toggle('Calendar').click()
  await toggle('Zoom').click()
  await page.keyboard.press('Escape')
  check(await page.getByRole('button', { name: 'View', exact: true }).evaluate(el => el === document.activeElement), 'Focus did not return to View')
  await page.getByRole('button', { name: '● Tracking', exact: true }).click()
  await page.getByRole('button', { name: 'Stop', exact: true }).click()
  check(await page.getByRole('form', { name: 'Stop tracking', exact: true }).isVisible(), 'Stop not reachable')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await toggle('Activity Tracking').click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await page.screenshot({ path: 'docs/design/day-visibility-172/web-mobile-dialog.png' })
  return 'Defaults, independent visibility, zoom retention, reload persistence, Escape/focus return, and Stop access passed.'
}

